project_name: unixtools
before:
  hooks:
    - go generate ./...

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
  mod: readonly

builds:
  - main: ./cmd/elvoke
    id: "elvoke"
    hooks:
      pre: go generate ./...
    binary: elvoke
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - main: ./cmd/mcd
    id: "mcd"
    binary: mcd
    hooks:
      pre: go generate ./...
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - main: ./cmd/pathctl
    hooks:
      pre: go generate ./...
    id: "pathctl"
    binary: pathctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - main: ./cmd/popbak
    id: "popbak"
    binary: popbak
    hooks:
      pre: go generate ./...
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - main: ./cmd/portup
    id: "portup"
    binary: portup
    hooks:
      pre: go generate ./...
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - main: ./cmd/pushbak
    id: "pushbak"
    binary: pushbak
    hooks:
      pre: go generate ./...
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - main: ./cmd/refiles
    id: "refiles"
    binary: refiles
    hooks:
      pre: go generate ./...
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - main: ./cmd/seq
    id: "seq"
    hooks:
      pre: go generate ./...
    binary: seq
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-UNRELEASED"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
