project_name: unixtools
before:
  hooks:
    - go mod tidy
    - go generate ./internal/...

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
  mod: readonly

builds:
  - id: elvoke
    main: ./cmd/elvoke
    binary: elvoke
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - id: mcd
    main: ./cmd/mcd
    binary: mcd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - id: pathctl
    main: ./cmd/pathctl
    binary: pathctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - id: popbak
    main: ./cmd/popbak
    binary: popbak
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - id: portup
    main: ./cmd/portup
    binary: portup
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - id: pushbak
    main: ./cmd/pushbak
    binary: pushbak
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - id: refiles
    main: ./cmd/refiles
    binary: refiles
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - id: seq
    main: ./cmd/seq
    binary: seq
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-UNRELEASED"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
