version: 2

project_name: unixtools
before:
  hooks:
    - go mod tidy
    - go generate ./...

gomod:
  module: al.essio.dev/tools/cmd
  mod: readonly

builds:
  - id: elvoke
    main: ./elvoke
    binary: elvoke
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - id: mcd
    main: ./mcd
    binary: mcd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - id: refiles
    main: ./refiles
    binary: refiles
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

  - id: seq
    main: ./seq
    binary: seq
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - openbsd
      - freebsd

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-UNRELEASED"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
